version: '3.7'
services:
  extract:
    build:
      context: extract
      args:
        - CHADWICK_VERSION
        - RETROSHEET_VERSION
        - BASEBALLDATABANK_VERSION
        - BUILD_ENV
    image: ${REPO}:extract-${VERSION}

  ddl:
    build:
      context: transform
      dockerfile: ddl.Dockerfile
      args:
        - VERSION
    image: ${REPO}:ddl-${VERSION}

  parquet:
    build:
      context: transform
      dockerfile: parquet.Dockerfile
      args:
        - VERSION
    image: ${REPO}:parquet-${VERSION}
    depends_on:
      - extract

  csv:
    build:
      context: transform
      dockerfile: csv.Dockerfile
      args:
        - VERSION
    image: ${REPO}:csv-${VERSION}
    depends_on:
      - extract

  clickhouse:
    build:
      context: load/clickhouse
      args:
        - VERSION
    image: ${REPO}:clickhouse-${VERSION}
    depends_on:
      - parquet
      - ddl

  drill:
    build:
      context: load/drill
      args:
        - VERSION
    image: ${REPO}:drill-${VERSION}
    depends_on:
      - parquet
      - ddl

  postgres:
    build:
      context: load/postgres
      args:
        - VERSION
    image: ${REPO}:postgres-${VERSION}
    depends_on:
      - csv
      - ddl

  postgres-cstore-fdw:
    build:
      context: load/postgres_cstore_fdw
      args:
        - VERSION
    image: ${REPO}:postgres-cstore-fdw-${VERSION}
    depends_on:
      - csv
      - ddl

  mysql:
    build:
      context: load/mysql
      args:
        - VERSION
    image: ${REPO}:mysql-${VERSION}
    depends_on:
      - csv
      - ddl

  sqlite:
    build:
      context: load/sqlite
      args:
        - VERSION
    image: ${REPO}:sqlite-${VERSION}
    depends_on:
      - csv
      - ddl
