version: '3.7'
services:

  boxball-extract:
    build: extract
    image: ${REPO}:extract-${VERSION}

  boxball-ddl:
    build:
      context: transform
      dockerfile: ddl.Dockerfile
    image: ${REPO}:ddl-${VERSION}

  boxball-parquet:
    build:
      context: transform
      dockerfile: parquet.Dockerfile
    image: ${REPO}:parquet-${VERSION}
    depends_on:
      - boxball-extract

  boxball-csv:
    build:
      context: transform
      dockerfile: csv.Dockerfile
    image: ${REPO}:csv-${VERSION}
    depends_on:
      - boxball-extract

  boxball-postgres:
    build: load/postgres
    image: ${REPO}:postgres-${VERSION}
    depends_on:
      - boxball-csv
      - boxball-ddl

  boxball-postgres-cstore-fdw:
    build: load/postgres_cstore_fdw
    image: ${REPO}:postgres-cstore-fdw-${VERSION}
    depends_on:
      - boxball-csv
      - boxball-ddl

  boxball-mysql:
    build: load/mysql
    image: ${REPO}:mysql-${VERSION}
    depends_on:
      - boxball-csv
      - boxball-ddl

  boxball-sqlite:
    build: load/sqlite
    image: ${REPO}:sqlite-${VERSION}
    depends_on:
      - boxball-csv
      - boxball-ddl
