version: '3.7'
services:
  dockerball-csv.gz:
    build: ./data_build
    image: dockerball-csv.gz:latest
  dockerball-postgres:
    build: ./target_builds/postgres
    image: dockerball-postgres:latest
    depends_on:
      - dockerball-csv.gz