version: '3.7'
x-extract:
  &extract
  build:
    context: extract
    args:
      - CHADWICK_VERSION
      - RETROSHEET_VERSION
      - BASEBALLDATABANK_VERSION
      - BUILD_ENV
  image: ${REPO}:extract-${VERSION}
x-ddl:
  &ddl
  build:
    context: transform
    dockerfile: ddl.Dockerfile
    args:
      - VERSION
  image: ${REPO}:ddl-${VERSION}
x-parquet:
  &parquet
  build:
    context: transform
    dockerfile: parquet.Dockerfile
    args:
      - VERSION
  image: ${REPO}:parquet-${VERSION}
  depends_on:
    - extract
x-csv:
  &csv
  build:
    context: transform
    dockerfile: csv.Dockerfile
    args:
      - VERSION
  image: ${REPO}:csv-${VERSION}
  depends_on:
    - extract

x-clickhouse:
  &clickhouse
  build:
    context: load/clickhouse
    dockerfile: ../Dockerfile
    target: clickhouse
    platforms:
      - "linux/amd64"
    args:
      - VERSION
  image: ${REPO}:clickhouse-${VERSION}
  volumes:
    - ~/boxball/clickhouse:/var/lib/clickhouse
  depends_on:
    - parquet
    - ddl

x-drill:
  &drill
  build:
    context: load/drill
    dockerfile: ../Dockerfile
    target: drill
    platforms:
      - "linux/amd64"
    args:
      - VERSION
  image: ${REPO}:drill-${VERSION}
  volumes:
    - ~/boxball/drill:/data
  depends_on:
    - parquet
    - ddl

x-postgres:
  &postgres
  build:
    context: load/postgres
    dockerfile: ../Dockerfile
    target: postgres
    platforms:
      - "linux/amd64"
    args:
      - VERSION
  image: ${REPO}:postgres-${VERSION}
  volumes:
    - ~/boxball/postgres:/var/lib/postgresql/data
  depends_on:
    - csv
    - ddl

x-postgres-cstore-fdw:
  &postgres-cstore-fdw
  build:
    context: load/postgres_cstore_fdw
    dockerfile: ../Dockerfile
    target: postgres-cstore-fdw
    platforms:
      - "linux/amd64"
    args:
      - VERSION
  image: ${REPO}:postgres-cstore-fdw-${VERSION}
  volumes:
    - ~/boxball/postgres-cstore-fdw:/var/lib/postgresql/data
  depends_on:
    - csv
    - ddl

x-mysql:
  &mysql
  build:
    context: load/mysql
    dockerfile: ../Dockerfile
    target: mysql
    platforms:
      - "linux/amd64"
    args:
      - VERSION
  image: ${REPO}:mysql-${VERSION}
  volumes:
    - ~/boxball/mysql:/var/lib/mysql
  depends_on:
    - csv
    - ddl

x-sqlite:
  &sqlite
  build:
    context: load
    target: sqlite
    platforms:
      - "linux/amd64"
    args:
      - VERSION
  image: ${REPO}:sqlite-${VERSION}
  volumes:
    - ~/boxball/sqlite:/db
  depends_on:
    - csv
    - ddl


services:
  extract:
    << : *extract
  extract-latest:
    << : *extract
    image: ${REPO}:extract-latest

  ddl:
    << : *ddl
  ddl-latest:
    << : *ddl
    image: ${REPO}:ddl-latest

  parquet:
    << : *parquet
  parquet-latest:
    << : *parquet
    image: ${REPO}:parquet-latest

  csv:
    << : *csv
  csv-latest:
    << : *csv
    image: ${REPO}:csv-latest

  clickhouse:
    << : *clickhouse
  clickhouse-latest:
    << : *clickhouse
    image: ${REPO}:clickhouse-latest

  drill:
    << : *drill
  drill-latest:
    << : *drill
    image: ${REPO}:drill-latest

  postgres:
    << : *postgres
  postgres-latest:
    << : *postgres
    image: ${REPO}:postgres-latest

  postgres-cstore-fdw:
    << : *postgres-cstore-fdw
  postgres-cstore-fdw-latest:
    << : *postgres-cstore-fdw
    image: ${REPO}:postgres-cstore-fdw-latest

  mysql:
    << : *mysql
  mysql-latest:
    << : *mysql
    image: ${REPO}:mysql-latest

  sqlite:
    << : *sqlite
  sqlite-latest:
    << : *sqlite
    image: ${REPO}:sqlite-latest
