# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  codecov: codecov/codecov@1.0.5


jobs:
    style:
      docker:
        - image: circleci/python:3.7.3-stretch
      steps:
        - checkout
        - run: |
            sudo pip install flake8==3.7.7
            flake8 .

    build:
      docker:
        - image: circleci/buildpack-deps:trusty
      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
            version: 18.06.0-ce
        - run:
            environment:
                BUILD_ENV: test
            command: docker-compose up -d


# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  build_and_test:
    jobs:
      - style
      - build:
          requires:
            - style
